version: 2
updates:
  # 启用Python依赖更新
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "pip"
      prefix-development: "pip-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # 忽略主要版本更新
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # 指定目标分支
    target-branch: "master"

  # 启用GitHub Actions更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    # 指定目标分支
    target-branch: "master"
