# These are supported funding model platforms

github: [xianyu564]
# ko_fi: # Leave this empty to disable
# liberapay: # Leave this empty to disable
# open_collective: # Leave this empty to disable
# otechie: # Leave this empty to disable
# patreon: # Leave this empty to disable
# tidelift: # Leave this empty to disable
# community_bridge: # Leave this empty to disable
# issuehunt: # Leave this empty to disable
# oswald: # Leave this empty to disable
# liberapay: # Leave this empty to disable
# custom: # Leave this empty to disable
